#!/bin/bash
set -eu -o pipefail
app_dir=$(dirname "$(readlink -e "$0")")
vcs_root=$( { git rev-parse --show-toplevel | xargs dirname ; } 2>/dev/null || dirname "$app_dir")
image="$(sed "s%^$vcs_root/%%" <<< "$app_dir" | tr '/.\- &' '_' | tr '[:upper:]' '[:lower:]')_sdk"

docker build -t "$image" "$app_dir/sdk/"

EXTRA_FLAGS=()
if tty -s
then
  EXTRA_FLAGS+=("-it")
fi

docker run \
  "${EXTRA_FLAGS[@]}" \
  --rm \
  -u "$(id -u):$(id -g)" \
  -v "$app_dir:/mnt" \
  -w "/mnt" \
  "$image" \
  make "$@"
