#!/bin/bash
set -eu -o pipefail
app_dir=$(dirname "$(readlink -e "$0")")
app=$(basename "$0")
if git status > /dev/null 2>&1
then
  vcs_root=$(git rev-parse --show-toplevel 2>/dev/null | xargs dirname)
  vcs_hash=$(git rev-parse --short HEAD)$(git diff --quiet || echo -dirty)
else
  vcs_root=$(dirname "$app_dir")
  vcs_hash="N/A"
fi
image="$(sed "s%^$vcs_root/%%" <<< "$app_dir" | tr '/.\- &' '_' | tr '[:upper:]' '[:lower:]')_3dsdk"

docker build -t "$image" "$app_dir/docker/"

flags=()
if tty -s
then
  flags+=("-it")
fi

if [ -n "${vcs_hash:-}" ]
then
  flags+=(--env "VCS_HASH=$vcs_hash")
fi

flags+=(--rm)
flags+=(--user "$(id -u):$(id -g)")
flags+=(--volume "$app_dir:/mnt")
flags+=(--workdir "/mnt")

if [ -n "${SDK_3D_ENABLE_GUI:-}" ]
then
  if [ -z "${DISPLAY:-}" ]
  then
    echo "$app: DISPLAY is not available" >&2
    exit 2
  fi
  echo "$app: enabling X11 display"

  flags+=(--env DISPLAY)
  flags+=(--env QT_X11_NO_MITSHM=1)
  for path in \
    "/tmp/.X11-unix" \
    "/run/user/$(id -u)/at-spi/bus_0"
  do
    if [ -e "$path" ]
    then
      flags+=(--volume "$path:$path:ro")
    fi
  done

  # proper home dir is needed for prusa-slicer to work in GUI mode
  user_dir=$app_dir/home
  mkdir -p "$user_dir"
  flags+=(--volume "$user_dir:/home/user")
  flags+=(--env HOME="/home/user")
fi

docker run \
  "${flags[@]}" \
  "$image" \
  "$@"
