#!/bin/bash
set -eu -o pipefail

app=$(basename "$0")
app_dir=$(dirname "$(readlink -e "$0")")

if [ $# -ne 1 ]
then
  echo "$app </out/dir>" >&2
  exit 2
fi
out_dir="$1"
shift 1

mkdir -p "$out_dir"
out_dir=$(readlink -e "$out_dir")

cd "$app_dir/template"
cp -rv \
  .gitignore \
  * \
  "$out_dir/"

cd "$out_dir"

if [ -f "project.mk" ]
then
  mv -v "project.mk" "project.config"
fi

if ! [ -f "project.config" ]
then
  cp -v "config/template/project.config" "project.config"
else
  sed 's/=.*/=/' "config/template/project.config" | \
    while read opt
    do
      grep -q "$opt" "project.config" || grep "$opt" "config/template/project.config" >> "project.config"
    done
fi
