#!/bin/bash
set -eu -o pipefail

app=$(basename "$0")
app_dir=$(dirname "$(readlink -e "$0")")

if [ $# -ne 1 ]
then
  echo "$app </out/dir>" >&2
  exit 2
fi
out_dir="$1"
shift 1

mkdir -p "$out_dir"
out_dir=$(readlink -e "$out_dir")

# remove old SDK dir, if present
if [ -f "$out_dir/sdk/merge_ini" ]
then
  rm -rf "$out_dir/sdk"
fi

cd "$app_dir/template"
cp -rv \
  .gitignore \
  * \
  "$out_dir/"

cd "$out_dir"

if [ -f "project.mk" ]
then
  mv -v "project.mk" "project.config"
fi

if ! [ -f "project.config" ]
then
  cp -v "config/template/project.config" "project.config"
else
  sed -i 's/:=/=/' *.config
  sed -i 's/^PRINTER=/PRINTER_3D=/' *.config
  sed 's/=.*/=/' "config/template/project.config" | \
    while read opt
    do
      grep -q "^$opt" "project.config" || grep "^$opt" "config/template/project.config" | tee -a "project.config"
    done
fi

# TPU has been renamed to TPU40D
for printer in anycubic_chiron voron_24_revo
do
  dir="config/printer/$printer/filament"
  if [ -d "$dir/tpu" ]
  then
    rm -rf "$dir/tpu"
    sed -i 's/^FILAMENT=tpu$/FILAMENT=tpu40d/' *.config
  fi
done
